Repository prgrms-be-devcourse/BE-04-DevTable, pull requests merged in 2023-09, with the labels that each got.

#9 [MDH-37] feat : 글로벌 예외 핸들러 작성
  src/main/java/com/mdh/devtable/global/error/ValidationError.java
  src/main/java/com/mdh/devtable/global/handler/GlobalControllerAdvice.java
Labels: Team-Allen, feat

#10 [MDH-40] docs : 풀리퀘스트 템플릿 추가
  .github/pull_request_template.md
Labels: Team-Allen, feat

#11 [MDH-41] chore : yaml 기본 설정
  src/main/resources/application.properties
  src/main/resources/static/docs/index.html
Labels: Team-Allen, chore

#21 [MDH-9] fix : 매장웨이팅 엔티티의 기본키 변경
  src/main/java/com/mdh/devtable/waiting/ShopWaiting.java
Labels: Team-Allen, fix

#25 [MDH-47] chore : develop 브랜치에 PR 등록 시 테스트 수행 자동화 스크립트 작성
  .github/workflows/veryfy-test-cases.yml
Labels: Team-Allen, chore

#32 [MDH-19] 매장의 실시간 웨이팅 확인
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/devtable.iml
  .idea/modules/devtable.main.iml
  .idea/modules/devtable.test.iml
  src/main/java/com/mdh/devtable/waiting/infra/persistence/PlainWaitingLine.java
  src/main/java/com/mdh/devtable/waiting/infra/persistence/WaitingLine.java
  src/test/java/com/mdh/devtable/waiting/WaitingLineTest.java
Labels: Team-Allen, feat

#34 [MDH-50] feat : 매장 웨이팅 상태변경 쓰기 락 적용(낙관적)
  .gitignore
  src/main/java/com/mdh/devtable/ownerwaitng/application/OwnerWaitingService.java
  src/main/java/com/mdh/devtable/ownerwaitng/presentaion/OwnerWaitingChangeRequest.java
  src/main/java/com/mdh/devtable/ownerwaitng/presentaion/dto/OwnerShopWaitingStatusChangeRequest.java
  src/main/java/com/mdh/devtable/waiting/domain/ShopWaiting.java
  src/test/java/com/mdh/devtable/ownerwaitng/application/OwnerWaitingLockTest.java
  src/test/java/com/mdh/devtable/ownerwaitng/application/OwnerWaitingServiceTest.java
Labels: Team-Allen, feat

#35 [MDH-53] feat : shop리포지토리 추가
  src/main/java/com/mdh/devtable/shop/infra/persistence/ShopRepository.java
Labels: Team-Allen, feat

#37 [MDH-48] feat : 매장 웨이팅 상태 변경 api 기능, 테스트 추가
  src/main/java/com/mdh/devtable/global/handler/GlobalControllerAdvice.java
  src/main/java/com/mdh/devtable/ownerwaitng/presentaion/controller/OwnerWaitingController.java
  src/main/java/com/mdh/devtable/ownerwaitng/presentaion/dto/OwnerWaitingStatusChangeRequest.java
  src/test/java/com/mdh/devtable/ownerwaitng/presentaion/controller/OwnerWaitingControllerTest.java
Labels: Team-Allen, feat

#40 [MDH-51] 유저 웨이팅 취소 엔드포인트 구현 및 테스트
  src/docs/asciidoc/index.adoc
  src/main/java/com/mdh/devtable/waiting/presentation/UserWaitingController.java
  src/test/java/com/mdh/devtable/waiting/presentation/UserWaitingControllerTest.java
Labels: Team-Allen, feat

#41 [MDH-54] docs : 누락된 restdocs adoc 추가
  src/docs/asciidoc/index.adoc
Labels: Team-Allen, chore

#42 [MDH-55] 테스트를 위한 객체 생성 팩토리 추가
  src/test/java/com/mdh/devtable/DataInitializerFactory.java
Labels: Team-Allen, feat

#43 [MDH-24] feat : 점주 웨이팅 상태 변경 기능, 테스트 추가
  src/main/java/com/mdh/devtable/ownerwaitng/application/OwnerWaitingService.java
  src/main/java/com/mdh/devtable/ownerwaitng/infra/persistence/OwnerWaitingRepository.java
  src/main/java/com/mdh/devtable/ownerwaitng/infra/persistence/OwnerWaitingRepositoryImpl.java
  src/test/java/com/mdh/devtable/ownerwaitng/application/OwnerWaitingServiceTest.java
Labels: feat

#45 [MDH-30] refactor : ownerwaiting 패키지 명 수정
  src/main/java/com/mdh/devtable/ownerwaiting/application/OwnerWaitingService.java
  src/main/java/com/mdh/devtable/ownerwaiting/infra/persistence/OwnerWaitingRepository.java
  src/main/java/com/mdh/devtable/ownerwaiting/infra/persistence/OwnerWaitingRepositoryImpl.java
  src/main/java/com/mdh/devtable/ownerwaiting/presentaion/controller/OwnerWaitingController.java
  src/main/java/com/mdh/devtable/ownerwaiting/presentaion/dto/OwnerShopWaitingStatusChangeRequest.java
  src/main/java/com/mdh/devtable/ownerwaiting/presentaion/dto/OwnerWaitingStatusChangeRequest.java
  src/test/java/com/mdh/devtable/ownerwaiting/application/OwnerWaitingLockTest.java
  src/test/java/com/mdh/devtable/ownerwaiting/application/OwnerWaitingServiceTest.java
  src/test/java/com/mdh/devtable/ownerwaiting/presentaion/controller/OwnerWaitingControllerTest.java
Labels: Team-Allen, feat

#48 [MDH-58] refactor : 테스트 코드 리팩토링(서비스 코드 MOCK기반으로 변경, 테스트용 생성자 팩토리 이용)
  src/test/java/com/mdh/devtable/ownerwaiting/application/OwnerWaitingServiceTest.java
  src/test/java/com/mdh/devtable/shop/ShopTest.java
  src/test/java/com/mdh/devtable/user/application/UserServiceTest.java
  src/test/java/com/mdh/devtable/user/domain/UserTest.java
  src/test/java/com/mdh/devtable/waiting/ShopWaitingTest.java
  src/test/java/com/mdh/devtable/waiting/WaitingTest.java
  src/test/java/com/mdh/devtable/waiting/application/WaitingServiceTest.java
Labels: Team-Allen, refactor

#46 [MDH-56] 유저는 상태별로 자신의 웨이팅을 조회 할 수 있다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/mdh/devtable/shop/ShopType.java
  src/main/java/com/mdh/devtable/waiting/application/WaitingService.java
  src/main/java/com/mdh/devtable/waiting/application/dto/UserWaitingResponse.java
  src/main/java/com/mdh/devtable/waiting/application/dto/WaitingResponse.java
  src/main/java/com/mdh/devtable/waiting/domain/ShopWaiting.java
  src/main/java/com/mdh/devtable/waiting/infra/persistence/WaitingRepository.java
  src/main/java/com/mdh/devtable/waiting/infra/persistence/dto/UserWaitingQueryDto.java
  src/main/java/com/mdh/devtable/waiting/presentation/UserWaitingController.java
  src/main/java/com/mdh/devtable/waiting/presentation/dto/MyWaitingsRequest.java
  src/test/java/com/mdh/devtable/waiting/WaitingTest.java
  src/test/java/com/mdh/devtable/waiting/application/WaitingServiceTest.java
  src/test/java/com/mdh/devtable/waiting/infra/persistence/WaitingRepositoryTest.java
  src/test/java/com/mdh/devtable/waiting/presentation/UserWaitingControllerTest.java
Labels: Team-Allen, feat

#60 [MDH-60] feat : 점주가 가지고 있는 매장의 웨이팅 조회 엔드포인트, rest docs 작성
  .gitignore
  src/docs/asciidoc/index.adoc
  src/main/java/com/mdh/devtable/global/util/RegularExpression.java
  src/main/java/com/mdh/devtable/ownerwaiting/application/OwnerWaitingService.java
  src/main/java/com/mdh/devtable/ownerwaiting/application/dto/WaitingInfoResponseForOwner.java
  src/main/java/com/mdh/devtable/ownerwaiting/infra/persistence/OwnerWaitingRepository.java
  src/main/java/com/mdh/devtable/ownerwaiting/infra/persistence/OwnerWaitingRepositoryImpl.java
  src/main/java/com/mdh/devtable/ownerwaiting/presentaion/controller/OwnerWaitingController.java
  src/main/java/com/mdh/devtable/waiting/infra/persistence/WaitingRepository.java
  src/main/resources/static/docs/index.html
  src/test/java/com/mdh/devtable/ownerwaiting/application/OwnerWaitingServiceTest.java
  src/test/java/com/mdh/devtable/ownerwaiting/infra/persistence/OwnerWaitingRepositoryTest.java
  src/test/java/com/mdh/devtable/ownerwaiting/presentaion/controller/OwnerWaitingControllerTest.java
  src/test/java/com/mdh/devtable/user/presentation/UserControllerTest.java
Labels: Team-Allen, feat

#53 [Front-end] 유저와 점주의 기능을 테스트 하기 위한 페이지를 구현
  .gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/App.test.js
  frontend/src/Main.jsx
  frontend/src/components/Header.jsx
  frontend/src/index.css
  frontend/src/index.jsx
  frontend/src/logo.svg
  frontend/src/pages/NotFound.jsx
  frontend/src/pages/OnwerPage.jsx
  frontend/src/pages/Root.jsx
  frontend/src/pages/UserPage.jsx
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: Team-Allen, feat

#75 [MDH-108] 유저를 위한 웨이팅 기능 구현 완료
  src/docs/asciidoc/index.adoc
  src/main/java/com/mdh/devtable/global/handler/GlobalControllerAdvice.java
  src/main/java/com/mdh/devtable/waiting/application/WaitingService.java
  src/main/java/com/mdh/devtable/waiting/domain/Waiting.java
  src/main/java/com/mdh/devtable/waiting/infra/persistence/PlainWaitingLine.java
  src/main/java/com/mdh/devtable/waiting/infra/persistence/WaitingLine.java
  src/main/java/com/mdh/devtable/waiting/infra/persistence/dto/WaitingInfo.java
  src/main/java/com/mdh/devtable/waiting/presentation/UserWaitingController.java
  src/test/java/com/mdh/devtable/waiting/WaitingLineTest.java
  src/test/java/com/mdh/devtable/waiting/application/WaitingServiceTest.java
  src/test/java/com/mdh/devtable/waiting/presentation/UserWaitingControllerTest.java
Labels: Team-Allen

#80 [MDH-68] 사용자는 자신이 등록한 예약을 취소 할 수 있다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/mdh/devtable/global/handler/GlobalControllerAdvice.java
  src/main/java/com/mdh/devtable/menu/application/MenuCategoryService.java
  src/main/java/com/mdh/devtable/menu/application/MenuService.java
  src/main/java/com/mdh/devtable/menu/application/MenuServiceValidator.java
  src/main/java/com/mdh/devtable/menu/domain/MealType.java
  src/main/java/com/mdh/devtable/menu/domain/Menu.java
  src/main/java/com/mdh/devtable/menu/domain/MenuCategory.java
  src/main/java/com/mdh/devtable/menu/domain/MenuType.java
  src/main/java/com/mdh/devtable/menu/infra/persistence/MenuCategoryRepository.java
  src/main/java/com/mdh/devtable/menu/infra/persistence/MenuRepository.java
  src/main/java/com/mdh/devtable/menu/persentation/MenuCategoryController.java
  src/main/java/com/mdh/devtable/menu/persentation/MenuController.java
  src/main/java/com/mdh/devtable/menu/persentation/dto/MenuCategoryCreateRequest.java
  src/main/java/com/mdh/devtable/menu/persentation/dto/MenuCreateRequest.java
  src/main/java/com/mdh/devtable/reservation/application/ReservationService.java
  src/main/java/com/mdh/devtable/reservation/domain/Reservation.java
  src/main/java/com/mdh/devtable/reservation/domain/ShopReservationDateTime.java
  src/main/java/com/mdh/devtable/waiting/application/WaitingService.java
  src/main/java/com/mdh/devtable/waiting/domain/Waiting.java
  src/main/java/com/mdh/devtable/waiting/infra/persistence/PlainWaitingLine.java
  src/main/java/com/mdh/devtable/waiting/infra/persistence/WaitingLine.java
  src/main/java/com/mdh/devtable/waiting/infra/persistence/WaitingRepository.java
  src/main/java/com/mdh/devtable/waiting/infra/persistence/dto/WaitingInfo.java
  src/main/java/com/mdh/devtable/waiting/presentation/UserWaitingController.java
  src/test/java/com/mdh/devtable/DataInitializerFactory.java
  src/test/java/com/mdh/devtable/menu/application/MenuCategoryServiceTest.java
  src/test/java/com/mdh/devtable/menu/application/MenuServiceTest.java
  src/test/java/com/mdh/devtable/menu/application/MenuServiceValidatorTest.java
  src/test/java/com/mdh/devtable/menu/domain/MenuCategoryTest.java
  src/test/java/com/mdh/devtable/menu/domain/MenuTest.java
  src/test/java/com/mdh/devtable/menu/persentation/MenuCategoryControllerTest.java
  src/test/java/com/mdh/devtable/menu/persentation/MenuControllerTest.java
  src/test/java/com/mdh/devtable/reservation/application/ReservationServiceTest.java
  src/test/java/com/mdh/devtable/reservation/domain/ReservationTest.java
  src/test/java/com/mdh/devtable/waiting/WaitingLineTest.java
  src/test/java/com/mdh/devtable/waiting/application/WaitingServiceTest.java
  src/test/java/com/mdh/devtable/waiting/presentation/UserWaitingControllerTest.java
Labels: Team-Allen, feat

#83 [MDH-HOTFIX] 좌석을 테이블 형태로 변경하기 위한 필드 추가
  src/main/java/com/mdh/devtable/reservation/domain/Seat.java
  src/test/java/com/mdh/devtable/reservation/domain/ShopReservationDateTimeSeatTest.java
Labels: Team-Allen, fix

#82 [MDH-117] 자신이 등록한 예약을 취소하는 엔드포인트 및 테스트 구현
  src/main/java/com/mdh/devtable/reservation/presentation/controller/ReservationController.java
  src/test/java/com/mdh/devtable/reservation/presentation/controller/ReservationControllerTest.java
Labels: Team-Allen, feat

#85 [MDH-62] 유저를 위한 예약 기능 구현 중간 PR
  src/main/java/com/mdh/devtable/reservation/application/ReservationService.java
  src/main/java/com/mdh/devtable/reservation/application/ReservationValidator.java
  src/main/java/com/mdh/devtable/reservation/controller/dto/ReservationCreateRequest.java
  src/main/java/com/mdh/devtable/reservation/domain/Reservation.java
  src/main/java/com/mdh/devtable/reservation/domain/ShopReservationDateTime.java
  src/main/java/com/mdh/devtable/reservation/presentation/controller/ReservationController.java
  src/test/java/com/mdh/devtable/DataInitializerFactory.java
  src/test/java/com/mdh/devtable/reservation/application/ReservationServiceTest.java
  src/test/java/com/mdh/devtable/reservation/application/ReservationValidatorTest.java
  src/test/java/com/mdh/devtable/reservation/domain/ReservationTest.java
  src/test/java/com/mdh/devtable/reservation/presentation/controller/ReservationControllerTest.java
Labels: Team-Allen, feat

#89 [MDH-69] 사용자는 자신의 예약을 예약 일로부터 하루 전까지 변경이 가능하다.
  src/main/java/com/mdh/devtable/reservation/application/ReservationService.java
  src/main/java/com/mdh/devtable/reservation/domain/Reservation.java
  src/main/java/com/mdh/devtable/reservation/presentation/controller/ReservationController.java
  src/main/java/com/mdh/devtable/reservation/presentation/dto/ReservationUpdateRequest.java
  src/test/java/com/mdh/devtable/reservation/application/ReservationServiceTest.java
  src/test/java/com/mdh/devtable/reservation/presentation/controller/ReservationControllerTest.java
Labels: Team-Allen, feat

#93 [MDH-66] feat & test : 예약을 선점, 확정, 취소 기능 추가 및 테스트
  src/main/java/com/mdh/devtable/DevTableApplication.java
  src/main/java/com/mdh/devtable/reservation/application/ReservationService.java
  src/main/java/com/mdh/devtable/reservation/controller/dto/ReservationCancelRequest.java
  src/main/java/com/mdh/devtable/reservation/controller/dto/ReservationPreemptiveRequest.java
  src/main/java/com/mdh/devtable/reservation/controller/dto/ReservationRegisterRequest.java
  src/main/java/com/mdh/devtable/reservation/domain/Reservation.java
  src/test/java/com/mdh/devtable/DataInitializerFactory.java
  src/test/java/com/mdh/devtable/reservation/application/ReservationServiceTest.java
Labels: Team-Allen, feat

#100 멀티 모듈에서 User 모듈이 제대로 올라가지 않는 버그 해결
  user/src/main/java/com/mdh/user/UserApplication.java
Labels: Team-Allen, fix
